# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/

name: Colab Tests (nightly)

on:
  schedule:
    - cron: "0 10 * * *" # 10am UTC (3am PST)
  workflow_dispatch:  # Allow manual triggers

jobs:
  run-colabs-nightly:
    name: Run Colabs Python Nightly
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.11'

      - name: Run Colab Notebooks
        run: |
          # Run each notebook in a fresh environment to prevent pip installs from one notebook corrupting the next
          for nb in colabs/torch_convert_and_quantize.ipynb colabs/getting_started.ipynb colabs/selective_quantization_isnet.ipynb; do
            python3 -m venv test_env
            source test_env/bin/activate
            python -m pip install --upgrade pip
            python -m pip install --index-url https://download.pytorch.org/whl/cpu torch torchvision
            python -m pip install tensorflow-cpu papermill jupyter matplotlib scikit-image
            papermill $nb /tmp/out -k python3 -p visualize_model 0
            deactivate
            rm -rf test_env
          done


      - name: Create Issue on Failure
        if: failure() && github.event_name != 'workflow_dispatch'
        uses: JasonEtco/create-an-issue@v2.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/workflows/action_failure_issue_template.md